version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --acl public-read --exclude "*.git/*" --exclude "buildspec.yml" . "s3://mcurlee.com"
     - aws s3 sync --acl public-read --exclude "*.git/*" --exclude "buildspec.yml" . "s3://www.mcurlee.com"
 post_build:
   commands:
     - echo "post_build step";
